apiVersion: apps/v1
kind: Deployment
metadata:
  name: appsignal-kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appsignal-kubernetes
  template:
    metadata:
      labels:
        app: appsignal-kubernetes
    spec:
      serviceAccountName: appsignal-kubernetes-service-account
      containers:
      - name: appsignal-kubernetes
        image: appsignal/appsignal-kubernetes:1.0.0-alpha.6
        imagePullPolicy: IfNotPresent
        env:
        - name: APPSIGNAL_API_KEY
          valueFrom:
            secretKeyRef:
              name: appsignal
              key: api-key
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: appsignal-kubernetes-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appsignal-kubernetes-role
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - "nodes/proxy"
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: appsignal-kubernetes-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: appsignal-kubernetes-role
subjects:
  - kind: ServiceAccount
    name: appsignal-kubernetes-service-account
    namespace: default
