---
# Source: appsignal-kubernetes/templates/deployment.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: appsignal
---
# Source: appsignal-kubernetes/templates/deployment.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: appsignal-kubernetes
  namespace: appsignal
  labels:
    app.kubernetes.io/name: appsignal-kubernetes
    app.kubernetes.io/instance: appsignal-kubernetes
    app.kubernetes.io/version: "1.2.0"
automountServiceAccountToken: true
---
# Source: appsignal-kubernetes/templates/deployment.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appsignal-kubernetes
  labels:
    app.kubernetes.io/name: appsignal-kubernetes
    app.kubernetes.io/instance: appsignal-kubernetes
    app.kubernetes.io/version: "1.2.0"
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs:
      - get
      - list
---
# Source: appsignal-kubernetes/templates/deployment.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: appsignal-kubernetes
  labels:
    app.kubernetes.io/name: appsignal-kubernetes
    app.kubernetes.io/instance: appsignal-kubernetes
    app.kubernetes.io/version: "1.2.0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: appsignal-kubernetes
subjects:
  - kind: ServiceAccount
    name: appsignal-kubernetes
    namespace: appsignal
---
# Source: appsignal-kubernetes/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appsignal-kubernetes
  namespace: appsignal
  labels:
    app.kubernetes.io/name: appsignal-kubernetes
    app.kubernetes.io/instance: appsignal-kubernetes
    app.kubernetes.io/version: "1.2.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: appsignal-kubernetes
      app.kubernetes.io/instance: appsignal-kubernetes
  template:
    metadata:
      labels:
        app.kubernetes.io/name: appsignal-kubernetes
        app.kubernetes.io/instance: appsignal-kubernetes
    spec:
      serviceAccountName: appsignal-kubernetes
      containers:
      - name: appsignal-kubernetes
        image: "appsignal/appsignal-kubernetes:1.2.0"
        imagePullPolicy: IfNotPresent
        env:
        - name: APPSIGNAL_API_KEY
          valueFrom:
            secretKeyRef:
              name: appsignal
              key: api-key
        - name: RUST_LOG
          value: info
        resources:
            {}
