{{/*
Expand the name of the chart.
*/}}
{{- define "appsignal-kubernetes.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Create a default fully qualified app name.
We truncate at 63 chars because some Kubernetes name fields are limited to this (by the DNS naming spec).
If release name contains chart name it will be used as a full name.
*/}}
{{- define "appsignal-kubernetes.fullname" -}}
{{- if .Values.fullnameOverride }}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- $name := default .Chart.Name .Values.nameOverride }}
{{- if contains $name .Release.Name }}
{{- .Release.Name | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}
{{- end }}

{{/*
Create chart name and version as used by the chart label.
*/}}
{{- define "appsignal-kubernetes.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Common labels
*/}}
{{- define "appsignal-kubernetes.labels" -}}
helm.sh/chart: {{ include "appsignal-kubernetes.chart" . }}
{{ include "appsignal-kubernetes.selectorLabels" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}

{{/*
Selector labels
*/}}
{{- define "appsignal-kubernetes.selectorLabels" -}}
app.kubernetes.io/name: {{ include "appsignal-kubernetes.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

{{/*
Create the name of the service account to use
*/}}
{{- define "appsignal-kubernetes.serviceAccountName" -}}
{{- if .Values.serviceAccount.create }}
{{- default (include "appsignal-kubernetes.fullname" .) .Values.serviceAccount.name }}
{{- else }}
{{- default "default" .Values.serviceAccount.name }}
{{- end }}
{{- end }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "appsignal-kubernetes.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "appsignal-kubernetes.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "appsignal-kubernetes.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "appsignal-kubernetes.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "appsignal-kubernetes.serviceAccountName" . }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: APPSIGNAL_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.appsignal.secretName }}
              key: {{ .Values.appsignal.secretKey }}
        - name: RUST_LOG
          value: {{ .Values.logLevel }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
---
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "appsignal-kubernetes.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "appsignal-kubernetes.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "appsignal-kubernetes.fullname" . }}
  labels:
    {{- include "appsignal-kubernetes.labels" . | nindent 4 }}
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "appsignal-kubernetes.fullname" . }}
  labels:
    {{- include "appsignal-kubernetes.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "appsignal-kubernetes.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "appsignal-kubernetes.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
