#!/usr/bin/env ruby
# frozen_string_literal: true

VERSION=ARGV[0]

File.write(
  "Cargo.toml",
  File.read("Cargo.toml").sub(/^version = ".*"$/, %(version = "#{VERSION}"))
)
File.write(
  "charts/appsignal-kubernetes/Chart.yaml",
  File.read("charts/appsignal-kubernetes/Chart.yaml").sub(/^version: .*$/, %(version: #{VERSION})))
File.write(
  "charts/appsignal-kubernetes/Chart.yaml",
  File.read("charts/appsignal-kubernetes/Chart.yaml").sub(/^appVersion: .*$/, %(appVersion: "#{VERSION}")))
system("rake helm:deployment")
