name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  schedule:
    - cron: 0 0 * * 1-5
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: "${{ !contains(github.ref, 'main')}}"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Check out all commits because we want to check out the gh-pages branch too

      - run: "git remote get-url --push origin"
      - name: "Login to Docker Hub"
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.CI_DOCKERHUB_USERNAME }}
          password: ${{ secrets.CI_DOCKERHUB_TOKEN }}
      - run: cargo clippy --verbose --tests --all-targets --all-features -- -D warnings
      - run: cargo fmt --check --verbose
      - run: cargo test --verbose

  build_release:
    name: "Build every target"
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: aarch64-unknown-linux-musl
          - target: x86_64-unknown-linux-musl
    steps:
      # Linux targets will cross compile on Docker images used by cross
      - name: "Login to Docker Hub"
        uses: docker/login-action@v3
        with:
          username: ${{secrets.CI_DOCKERHUB_USERNAME}}
          password: ${{secrets.CI_DOCKERHUB_TOKEN}}

      - name: "Checkout project"
        uses: actions/checkout@v4

      - name: "Build target for ${{matrix.target}}"
        run: "rake build:target:${{matrix.target}}"
