name: Publish a release
on:
  # Trigger this release via the GitHub Actions interface for this workflow
  workflow_dispatch:

jobs:
  publish:
    name: "Publish the release"
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout the project"
        uses: actions/checkout@v4

      - name: "Checkout Mono"
        uses: actions/checkout@v4
        with:
          repository: "appsignal/mono"
          path: "tmp/mono"

      - name: "Create version"
        id: version
        run: |
          tmp/mono/bin/mono publish --no-git --no-package-push --yes

          export RELEASE_VERSION="$(script/read_version)"
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> "$GITHUB_OUTPUT"

      - name: "Git commit changes"
        run: |
          git add .
          git commit \
            --message "Release version ${{steps.version.outputs.RELEASE_VERSION}}" \
            --message "Update version number and CHANGELOG.md."
          git tag "v${{steps.version.outputs.RELEASE_VERSION}}"
