name: Publish a release
on:
  # Trigger this release via the GitHub Actions interface for this workflow
  workflow_dispatch:

env:
  PUBLISH_GIT_USERNAME: "AppSignal release bot"
  PUBLISH_GIT_EMAIL: "support+build-sign@appsignal.com"

jobs:
  publish:
    name: "Publish the release"
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout the project"
        uses: actions/checkout@v4
        with:
          ssh-key: "${{secrets.PUBLISH_DEPLOY_KEY}}"

      - name: "Checkout Mono"
        uses: actions/checkout@v4
        with:
          repository: "appsignal/mono"
          path: "tmp/mono"

      - name: "Configure Git"
        run: |
          git config --global user.name "$PUBLISH_GIT_USERNAME (as ${{github.actor}})"
          git config --global user.email "$PUBLISH_GIT_EMAIL"

      - name: "Create version"
        id: version
        run: |
          tmp/mono/bin/mono publish --no-git --no-package-push --yes

          export RELEASE_VERSION="$(script/read_version)"
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> "$GITHUB_OUTPUT"

      - name: "Git commit changes"
        run: |
          git add .
          git commit \
            --message "Release version ${{steps.version.outputs.RELEASE_VERSION}}" \
            --message "Update version number and CHANGELOG.md."
          git tag "v${{steps.version.outputs.RELEASE_VERSION}}"

      - name: "Login to Docker Hub"
        uses: docker/login-action@v3
        with:
          username: ${{secrets.PUBLISH_DOCKERHUB_USERNAME}}
          password: ${{secrets.PUBLISH_DOCKERHUB_TOKEN}}

      - name: "Build and publish to Docker Hub"
        run: rake publish

      - name: "Push release to repository"
        run: git push origin ${{github.ref_name}} "v${{steps.version.outputs.RELEASE_VERSION}}"
