name: Publish a release
on:
  # Trigger this release via the GitHub Actions interface for this workflow
  workflow_dispatch:

jobs:
  publish:
    name: "Publish the release"
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout the project"
        uses: actions/checkout@v4

      - name: "Checkout Mono"
        uses: actions/checkout@v4
        with:
          repository: "appsignal/mono"
          path: "tmp/mono"

      - name: "Create version"
        id: version
        run: |
          tmp/mono/bin/mono publish --no-git --no-package-push --yes
